FROM golang:1.25

COPY go.mod go.sum /go/src/github.com/tatsuworks/gateway/
RUN cd /go/src/github.com/tatsuworks/gateway && go mod download

COPY . /go/src/github.com/tatsuworks/gateway
ENV GO111MODULE=on

RUN cd /go/src/github.com/tatsuworks/gateway/cmd/state && go build -o /go/state .

FROM ubuntu:24.04
RUN apt update && apt install -y adduser

COPY --from=0 /go/state /
COPY entrypoint-state.sh /
CMD [ "/entrypoint-state.sh" ]
