// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: member.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Member struct {
	UserId   string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId  string   `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	JoinedAt string   `protobuf:"bytes,3,opt,name=JoinedAt,proto3" json:"JoinedAt,omitempty"`
	Nick     string   `protobuf:"bytes,4,opt,name=nick,proto3" json:"nick,omitempty"`
	Deaf     bool     `protobuf:"varint,5,opt,name=deaf,proto3" json:"deaf,omitempty"`
	Mute     bool     `protobuf:"varint,6,opt,name=mute,proto3" json:"mute,omitempty"`
	Roles    []string `protobuf:"bytes,7,rep,name=roles" json:"roles,omitempty"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Member.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return m.Size()
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Member) GetGuildId() string {
	if m != nil {
		return m.GuildId
	}
	return ""
}

func (m *Member) GetJoinedAt() string {
	if m != nil {
		return m.JoinedAt
	}
	return ""
}

func (m *Member) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *Member) GetDeaf() bool {
	if m != nil {
		return m.Deaf
	}
	return false
}

func (m *Member) GetMute() bool {
	if m != nil {
		return m.Mute
	}
	return false
}

func (m *Member) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type MemberUpdate struct {
	Nick  *BytesValue                      `protobuf:"bytes,1,opt,name=nick" json:"nick,omitempty"`
	Deaf  *BoolValue                       `protobuf:"bytes,2,opt,name=deaf" json:"deaf,omitempty"`
	Mute  *BoolValue                       `protobuf:"bytes,3,opt,name=mute" json:"mute,omitempty"`
	Roles []*MemberUpdate_RoleModification `protobuf:"bytes,4,rep,name=roles" json:"roles,omitempty"`
}

func (m *MemberUpdate) Reset()         { *m = MemberUpdate{} }
func (m *MemberUpdate) String() string { return proto.CompactTextString(m) }
func (*MemberUpdate) ProtoMessage()    {}
func (*MemberUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{1}
}
func (m *MemberUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MemberUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MemberUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MemberUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUpdate.Merge(dst, src)
}
func (m *MemberUpdate) XXX_Size() int {
	return m.Size()
}
func (m *MemberUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUpdate proto.InternalMessageInfo

func (m *MemberUpdate) GetNick() *BytesValue {
	if m != nil {
		return m.Nick
	}
	return nil
}

func (m *MemberUpdate) GetDeaf() *BoolValue {
	if m != nil {
		return m.Deaf
	}
	return nil
}

func (m *MemberUpdate) GetMute() *BoolValue {
	if m != nil {
		return m.Mute
	}
	return nil
}

func (m *MemberUpdate) GetRoles() []*MemberUpdate_RoleModification {
	if m != nil {
		return m.Roles
	}
	return nil
}

type MemberUpdate_RoleModification struct {
	// Types that are valid to be assigned to Modification:
	//	*MemberUpdate_RoleModification_RoleAdd
	//	*MemberUpdate_RoleModification_RoleRemove
	Modification isMemberUpdate_RoleModification_Modification `protobuf_oneof:"Modification"`
}

func (m *MemberUpdate_RoleModification) Reset()         { *m = MemberUpdate_RoleModification{} }
func (m *MemberUpdate_RoleModification) String() string { return proto.CompactTextString(m) }
func (*MemberUpdate_RoleModification) ProtoMessage()    {}
func (*MemberUpdate_RoleModification) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{1, 0}
}
func (m *MemberUpdate_RoleModification) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MemberUpdate_RoleModification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MemberUpdate_RoleModification.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MemberUpdate_RoleModification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUpdate_RoleModification.Merge(dst, src)
}
func (m *MemberUpdate_RoleModification) XXX_Size() int {
	return m.Size()
}
func (m *MemberUpdate_RoleModification) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUpdate_RoleModification.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUpdate_RoleModification proto.InternalMessageInfo

type isMemberUpdate_RoleModification_Modification interface {
	isMemberUpdate_RoleModification_Modification()
	MarshalTo([]byte) (int, error)
	Size() int
}

type MemberUpdate_RoleModification_RoleAdd struct {
	RoleAdd string `protobuf:"bytes,1,opt,name=role_add,json=roleAdd,proto3,oneof"`
}
type MemberUpdate_RoleModification_RoleRemove struct {
	RoleRemove string `protobuf:"bytes,2,opt,name=role_remove,json=roleRemove,proto3,oneof"`
}

func (*MemberUpdate_RoleModification_RoleAdd) isMemberUpdate_RoleModification_Modification()    {}
func (*MemberUpdate_RoleModification_RoleRemove) isMemberUpdate_RoleModification_Modification() {}

func (m *MemberUpdate_RoleModification) GetModification() isMemberUpdate_RoleModification_Modification {
	if m != nil {
		return m.Modification
	}
	return nil
}

func (m *MemberUpdate_RoleModification) GetRoleAdd() string {
	if x, ok := m.GetModification().(*MemberUpdate_RoleModification_RoleAdd); ok {
		return x.RoleAdd
	}
	return ""
}

func (m *MemberUpdate_RoleModification) GetRoleRemove() string {
	if x, ok := m.GetModification().(*MemberUpdate_RoleModification_RoleRemove); ok {
		return x.RoleRemove
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MemberUpdate_RoleModification) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MemberUpdate_RoleModification_OneofMarshaler, _MemberUpdate_RoleModification_OneofUnmarshaler, _MemberUpdate_RoleModification_OneofSizer, []interface{}{
		(*MemberUpdate_RoleModification_RoleAdd)(nil),
		(*MemberUpdate_RoleModification_RoleRemove)(nil),
	}
}

func _MemberUpdate_RoleModification_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MemberUpdate_RoleModification)
	// Modification
	switch x := m.Modification.(type) {
	case *MemberUpdate_RoleModification_RoleAdd:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.RoleAdd)
	case *MemberUpdate_RoleModification_RoleRemove:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.RoleRemove)
	case nil:
	default:
		return fmt.Errorf("MemberUpdate_RoleModification.Modification has unexpected type %T", x)
	}
	return nil
}

func _MemberUpdate_RoleModification_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MemberUpdate_RoleModification)
	switch tag {
	case 1: // Modification.role_add
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Modification = &MemberUpdate_RoleModification_RoleAdd{x}
		return true, err
	case 2: // Modification.role_remove
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Modification = &MemberUpdate_RoleModification_RoleRemove{x}
		return true, err
	default:
		return false, nil
	}
}

func _MemberUpdate_RoleModification_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MemberUpdate_RoleModification)
	// Modification
	switch x := m.Modification.(type) {
	case *MemberUpdate_RoleModification_RoleAdd:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.RoleAdd)))
		n += len(x.RoleAdd)
	case *MemberUpdate_RoleModification_RoleRemove:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.RoleRemove)))
		n += len(x.RoleRemove)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetMemberRequest struct {
	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId string `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (m *GetMemberRequest) Reset()         { *m = GetMemberRequest{} }
func (m *GetMemberRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemberRequest) ProtoMessage()    {}
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{2}
}
func (m *GetMemberRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetMemberRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberRequest.Merge(dst, src)
}
func (m *GetMemberRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberRequest proto.InternalMessageInfo

func (m *GetMemberRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetMemberRequest) GetGuildId() string {
	if m != nil {
		return m.GuildId
	}
	return ""
}

type GetMemberResponse struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *GetMemberResponse) Reset()         { *m = GetMemberResponse{} }
func (m *GetMemberResponse) String() string { return proto.CompactTextString(m) }
func (*GetMemberResponse) ProtoMessage()    {}
func (*GetMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{3}
}
func (m *GetMemberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetMemberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberResponse.Merge(dst, src)
}
func (m *GetMemberResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberResponse proto.InternalMessageInfo

func (m *GetMemberResponse) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type SetMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *SetMemberRequest) Reset()         { *m = SetMemberRequest{} }
func (m *SetMemberRequest) String() string { return proto.CompactTextString(m) }
func (*SetMemberRequest) ProtoMessage()    {}
func (*SetMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{4}
}
func (m *SetMemberRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetMemberRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SetMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMemberRequest.Merge(dst, src)
}
func (m *SetMemberRequest) XXX_Size() int {
	return m.Size()
}
func (m *SetMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMemberRequest proto.InternalMessageInfo

func (m *SetMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type SetMemberResponse struct {
}

func (m *SetMemberResponse) Reset()         { *m = SetMemberResponse{} }
func (m *SetMemberResponse) String() string { return proto.CompactTextString(m) }
func (*SetMemberResponse) ProtoMessage()    {}
func (*SetMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{5}
}
func (m *SetMemberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetMemberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SetMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMemberResponse.Merge(dst, src)
}
func (m *SetMemberResponse) XXX_Size() int {
	return m.Size()
}
func (m *SetMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMemberResponse proto.InternalMessageInfo

type UpdateMemberRequest struct {
	UserId  string        `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId string        `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Member  *MemberUpdate `protobuf:"bytes,3,opt,name=member" json:"member,omitempty"`
}

func (m *UpdateMemberRequest) Reset()         { *m = UpdateMemberRequest{} }
func (m *UpdateMemberRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMemberRequest) ProtoMessage()    {}
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{6}
}
func (m *UpdateMemberRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateMemberRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *UpdateMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMemberRequest.Merge(dst, src)
}
func (m *UpdateMemberRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMemberRequest proto.InternalMessageInfo

func (m *UpdateMemberRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateMemberRequest) GetGuildId() string {
	if m != nil {
		return m.GuildId
	}
	return ""
}

func (m *UpdateMemberRequest) GetMember() *MemberUpdate {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberResponse struct {
}

func (m *UpdateMemberResponse) Reset()         { *m = UpdateMemberResponse{} }
func (m *UpdateMemberResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMemberResponse) ProtoMessage()    {}
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{7}
}
func (m *UpdateMemberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateMemberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *UpdateMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMemberResponse.Merge(dst, src)
}
func (m *UpdateMemberResponse) XXX_Size() int {
	return m.Size()
}
func (m *UpdateMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMemberResponse proto.InternalMessageInfo

type DeleteMemberRequest struct {
	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId string `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (m *DeleteMemberRequest) Reset()         { *m = DeleteMemberRequest{} }
func (m *DeleteMemberRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMemberRequest) ProtoMessage()    {}
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{8}
}
func (m *DeleteMemberRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteMemberRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *DeleteMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMemberRequest.Merge(dst, src)
}
func (m *DeleteMemberRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMemberRequest proto.InternalMessageInfo

func (m *DeleteMemberRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteMemberRequest) GetGuildId() string {
	if m != nil {
		return m.GuildId
	}
	return ""
}

type DeleteMemberResponse struct {
}

func (m *DeleteMemberResponse) Reset()         { *m = DeleteMemberResponse{} }
func (m *DeleteMemberResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMemberResponse) ProtoMessage()    {}
func (*DeleteMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_member_53767bd4152ed625, []int{9}
}
func (m *DeleteMemberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteMemberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *DeleteMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMemberResponse.Merge(dst, src)
}
func (m *DeleteMemberResponse) XXX_Size() int {
	return m.Size()
}
func (m *DeleteMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMemberResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Member)(nil), "state.Member")
	proto.RegisterType((*MemberUpdate)(nil), "state.MemberUpdate")
	proto.RegisterType((*MemberUpdate_RoleModification)(nil), "state.MemberUpdate.RoleModification")
	proto.RegisterType((*GetMemberRequest)(nil), "state.GetMemberRequest")
	proto.RegisterType((*GetMemberResponse)(nil), "state.GetMemberResponse")
	proto.RegisterType((*SetMemberRequest)(nil), "state.SetMemberRequest")
	proto.RegisterType((*SetMemberResponse)(nil), "state.SetMemberResponse")
	proto.RegisterType((*UpdateMemberRequest)(nil), "state.UpdateMemberRequest")
	proto.RegisterType((*UpdateMemberResponse)(nil), "state.UpdateMemberResponse")
	proto.RegisterType((*DeleteMemberRequest)(nil), "state.DeleteMemberRequest")
	proto.RegisterType((*DeleteMemberResponse)(nil), "state.DeleteMemberResponse")
}
func (m *Member) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Member) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.UserId)))
		i += copy(dAtA[i:], m.UserId)
	}
	if len(m.GuildId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.GuildId)))
		i += copy(dAtA[i:], m.GuildId)
	}
	if len(m.JoinedAt) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.JoinedAt)))
		i += copy(dAtA[i:], m.JoinedAt)
	}
	if len(m.Nick) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.Nick)))
		i += copy(dAtA[i:], m.Nick)
	}
	if m.Deaf {
		dAtA[i] = 0x28
		i++
		if m.Deaf {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Mute {
		dAtA[i] = 0x30
		i++
		if m.Mute {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Roles) > 0 {
		for _, s := range m.Roles {
			dAtA[i] = 0x3a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *MemberUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MemberUpdate) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Nick != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMember(dAtA, i, uint64(m.Nick.Size()))
		n1, err := m.Nick.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Deaf != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMember(dAtA, i, uint64(m.Deaf.Size()))
		n2, err := m.Deaf.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Mute != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMember(dAtA, i, uint64(m.Mute.Size()))
		n3, err := m.Mute.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.Roles) > 0 {
		for _, msg := range m.Roles {
			dAtA[i] = 0x22
			i++
			i = encodeVarintMember(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *MemberUpdate_RoleModification) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MemberUpdate_RoleModification) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Modification != nil {
		nn4, err := m.Modification.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn4
	}
	return i, nil
}

func (m *MemberUpdate_RoleModification_RoleAdd) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	dAtA[i] = 0xa
	i++
	i = encodeVarintMember(dAtA, i, uint64(len(m.RoleAdd)))
	i += copy(dAtA[i:], m.RoleAdd)
	return i, nil
}
func (m *MemberUpdate_RoleModification_RoleRemove) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	dAtA[i] = 0x12
	i++
	i = encodeVarintMember(dAtA, i, uint64(len(m.RoleRemove)))
	i += copy(dAtA[i:], m.RoleRemove)
	return i, nil
}
func (m *GetMemberRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetMemberRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.UserId)))
		i += copy(dAtA[i:], m.UserId)
	}
	if len(m.GuildId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.GuildId)))
		i += copy(dAtA[i:], m.GuildId)
	}
	return i, nil
}

func (m *GetMemberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetMemberResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Member != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMember(dAtA, i, uint64(m.Member.Size()))
		n5, err := m.Member.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}

func (m *SetMemberRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetMemberRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Member != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMember(dAtA, i, uint64(m.Member.Size()))
		n6, err := m.Member.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}

func (m *SetMemberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetMemberResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *UpdateMemberRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateMemberRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.UserId)))
		i += copy(dAtA[i:], m.UserId)
	}
	if len(m.GuildId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.GuildId)))
		i += copy(dAtA[i:], m.GuildId)
	}
	if m.Member != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMember(dAtA, i, uint64(m.Member.Size()))
		n7, err := m.Member.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}

func (m *UpdateMemberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateMemberResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *DeleteMemberRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteMemberRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.UserId)))
		i += copy(dAtA[i:], m.UserId)
	}
	if len(m.GuildId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMember(dAtA, i, uint64(len(m.GuildId)))
		i += copy(dAtA[i:], m.GuildId)
	}
	return i, nil
}

func (m *DeleteMemberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteMemberResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeVarintMember(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Member) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	l = len(m.GuildId)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	l = len(m.JoinedAt)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	l = len(m.Nick)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	if m.Deaf {
		n += 2
	}
	if m.Mute {
		n += 2
	}
	if len(m.Roles) > 0 {
		for _, s := range m.Roles {
			l = len(s)
			n += 1 + l + sovMember(uint64(l))
		}
	}
	return n
}

func (m *MemberUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nick != nil {
		l = m.Nick.Size()
		n += 1 + l + sovMember(uint64(l))
	}
	if m.Deaf != nil {
		l = m.Deaf.Size()
		n += 1 + l + sovMember(uint64(l))
	}
	if m.Mute != nil {
		l = m.Mute.Size()
		n += 1 + l + sovMember(uint64(l))
	}
	if len(m.Roles) > 0 {
		for _, e := range m.Roles {
			l = e.Size()
			n += 1 + l + sovMember(uint64(l))
		}
	}
	return n
}

func (m *MemberUpdate_RoleModification) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Modification != nil {
		n += m.Modification.Size()
	}
	return n
}

func (m *MemberUpdate_RoleModification_RoleAdd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RoleAdd)
	n += 1 + l + sovMember(uint64(l))
	return n
}
func (m *MemberUpdate_RoleModification_RoleRemove) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RoleRemove)
	n += 1 + l + sovMember(uint64(l))
	return n
}
func (m *GetMemberRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	l = len(m.GuildId)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	return n
}

func (m *GetMemberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Member != nil {
		l = m.Member.Size()
		n += 1 + l + sovMember(uint64(l))
	}
	return n
}

func (m *SetMemberRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Member != nil {
		l = m.Member.Size()
		n += 1 + l + sovMember(uint64(l))
	}
	return n
}

func (m *SetMemberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *UpdateMemberRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	l = len(m.GuildId)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	if m.Member != nil {
		l = m.Member.Size()
		n += 1 + l + sovMember(uint64(l))
	}
	return n
}

func (m *UpdateMemberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *DeleteMemberRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	l = len(m.GuildId)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	return n
}

func (m *DeleteMemberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovMember(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMember(x uint64) (n int) {
	return sovMember(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Member) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Member: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Member: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuildId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuildId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JoinedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nick", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nick = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deaf", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Deaf = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mute", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Mute = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roles", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roles = append(m.Roles, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MemberUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MemberUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MemberUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nick", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Nick == nil {
				m.Nick = &BytesValue{}
			}
			if err := m.Nick.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deaf", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Deaf == nil {
				m.Deaf = &BoolValue{}
			}
			if err := m.Deaf.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mute", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Mute == nil {
				m.Mute = &BoolValue{}
			}
			if err := m.Mute.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roles = append(m.Roles, &MemberUpdate_RoleModification{})
			if err := m.Roles[len(m.Roles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MemberUpdate_RoleModification) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoleModification: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoleModification: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleAdd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Modification = &MemberUpdate_RoleModification_RoleAdd{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleRemove", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Modification = &MemberUpdate_RoleModification_RoleRemove{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetMemberRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetMemberRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetMemberRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuildId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuildId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetMemberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetMemberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetMemberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Member", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Member == nil {
				m.Member = &Member{}
			}
			if err := m.Member.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetMemberRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetMemberRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetMemberRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Member", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Member == nil {
				m.Member = &Member{}
			}
			if err := m.Member.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetMemberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetMemberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetMemberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateMemberRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateMemberRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateMemberRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuildId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuildId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Member", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Member == nil {
				m.Member = &MemberUpdate{}
			}
			if err := m.Member.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateMemberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateMemberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateMemberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteMemberRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteMemberRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteMemberRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuildId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuildId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteMemberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteMemberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteMemberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMember(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMember
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMember
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMember
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMember(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMember = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMember   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("member.proto", fileDescriptor_member_53767bd4152ed625) }

var fileDescriptor_member_53767bd4152ed625 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xed, 0xfc, 0x71, 0xd2, 0x49, 0xa8, 0x92, 0x4d, 0x05, 0x26, 0x20, 0x2b, 0x58, 0x41,
	0x8a, 0x84, 0xe4, 0x43, 0x39, 0xd1, 0x5b, 0x23, 0x04, 0x0d, 0x52, 0x2f, 0x5b, 0xc1, 0x81, 0x4b,
	0x65, 0x77, 0xa7, 0xc8, 0xc2, 0xf6, 0x1a, 0xef, 0xba, 0x88, 0xb7, 0xe0, 0x15, 0xb8, 0xf2, 0x24,
	0x1c, 0x7b, 0xe4, 0x88, 0x92, 0x17, 0x41, 0xfb, 0x27, 0x51, 0x12, 0x81, 0x84, 0x80, 0xdb, 0xce,
	0xf7, 0x4d, 0xf6, 0xfb, 0xed, 0x4c, 0x0c, 0xfd, 0x1c, 0xf3, 0x04, 0xab, 0xa8, 0xac, 0xb8, 0xe4,
	0xa4, 0x2d, 0x64, 0x2c, 0x71, 0x7c, 0xf8, 0xb1, 0x8a, 0xcb, 0x12, 0x2b, 0x61, 0xe4, 0xf0, 0xab,
	0x0b, 0xde, 0xb9, 0xee, 0x23, 0xf7, 0xa0, 0x53, 0x0b, 0xac, 0x2e, 0x53, 0xe6, 0xbb, 0x13, 0x77,
	0x76, 0x40, 0x3d, 0x55, 0x2e, 0x18, 0xb9, 0x0f, 0xdd, 0x77, 0x75, 0x9a, 0x31, 0xe5, 0x34, 0xb4,
	0xd3, 0xd1, 0xf5, 0x82, 0x91, 0x31, 0x74, 0x5f, 0xf1, 0xb4, 0x40, 0x76, 0x2a, 0xfd, 0xa6, 0xb6,
	0x36, 0x35, 0x21, 0xd0, 0x2a, 0xd2, 0xab, 0xf7, 0x7e, 0x4b, 0xeb, 0xfa, 0xac, 0x34, 0x86, 0xf1,
	0xb5, 0xdf, 0x9e, 0xb8, 0xb3, 0x2e, 0xd5, 0x67, 0xa5, 0xe5, 0xb5, 0x44, 0xdf, 0x33, 0x9a, 0x3a,
	0x93, 0x23, 0x68, 0x57, 0x3c, 0x43, 0xe1, 0x77, 0x26, 0xcd, 0xd9, 0x01, 0x35, 0x45, 0xf8, 0xa5,
	0x01, 0x7d, 0x03, 0xfb, 0xba, 0x64, 0xb1, 0x44, 0xf2, 0xd8, 0x46, 0x28, 0xde, 0xde, 0xf1, 0x30,
	0xd2, 0x6f, 0x8c, 0xe6, 0x9f, 0x24, 0x8a, 0x37, 0x71, 0x56, 0xa3, 0x4d, 0x9d, 0xda, 0xd4, 0x86,
	0x6e, 0x1b, 0xac, 0xdb, 0x38, 0xcf, 0x6c, 0x97, 0xe6, 0x98, 0x5a, 0x8e, 0xe6, 0xef, 0xba, 0x34,
	0xd9, 0xc9, 0x9a, 0xac, 0x35, 0x69, 0xce, 0x7a, 0xc7, 0x53, 0xdb, 0xb6, 0x8d, 0x15, 0x51, 0x9e,
	0xe1, 0x39, 0x67, 0xe9, 0x75, 0x7a, 0x15, 0xcb, 0x94, 0x17, 0x96, 0x7f, 0x9c, 0xc0, 0x60, 0xdf,
	0x22, 0x0f, 0xa0, 0xab, 0xcc, 0xcb, 0x98, 0xd9, 0xb1, 0x9f, 0x39, 0xb4, 0xa3, 0x94, 0x53, 0xc6,
	0xc8, 0x23, 0xe8, 0x69, 0xb3, 0xc2, 0x9c, 0xdf, 0xa0, 0x19, 0xfe, 0x99, 0x43, 0x41, 0x89, 0x54,
	0x6b, 0xf3, 0x43, 0xe8, 0x6f, 0xdf, 0x17, 0xbe, 0x80, 0xc1, 0x4b, 0x94, 0x06, 0x87, 0xe2, 0x87,
	0x1a, 0x85, 0xfc, 0x9b, 0xcd, 0x86, 0x27, 0x30, 0xdc, 0xba, 0x47, 0x94, 0xbc, 0x10, 0x6a, 0xde,
	0x9e, 0xf9, 0x53, 0xd9, 0x89, 0xdf, 0xd9, 0x79, 0x3d, 0xb5, 0x66, 0xf8, 0x0c, 0x06, 0x17, 0xfb,
	0x0c, 0x7f, 0xf8, 0xd3, 0x11, 0x0c, 0x2f, 0xf6, 0x63, 0xc3, 0x1b, 0x18, 0x99, 0xc9, 0xfe, 0xf3,
	0xb3, 0xc8, 0x93, 0x0d, 0x86, 0x59, 0xf3, 0xe8, 0x17, 0xfb, 0xdb, 0xc0, 0xdc, 0x85, 0xa3, 0xdd,
	0x5c, 0xcb, 0xb3, 0x80, 0xd1, 0x73, 0xcc, 0xf0, 0x3f, 0xf0, 0xa8, 0x88, 0xdd, 0xab, 0x4c, 0xc4,
	0xfc, 0xe1, 0xb7, 0x65, 0xe0, 0xde, 0x2e, 0x03, 0xf7, 0xc7, 0x32, 0x70, 0x3f, 0xaf, 0x02, 0xe7,
	0x76, 0x15, 0x38, 0xdf, 0x57, 0x81, 0xf3, 0xb6, 0x51, 0x26, 0x89, 0xa7, 0x3f, 0xde, 0xa7, 0x3f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x52, 0x6a, 0x50, 0x6b, 0xe3, 0x03, 0x00, 0x00,
}
