// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: state.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StateClient is the client API for State service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateClient interface {
	GetChannel(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*GetChannelResponse, error)
	SetChannel(ctx context.Context, in *SetChannelRequest, opts ...grpc.CallOption) (*SetChannelResponse, error)
	UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*UpdateChannelResponse, error)
	DeleteChannel(ctx context.Context, in *DeleteChannelRequest, opts ...grpc.CallOption) (*DeleteChannelResponse, error)
	SetChannelChunk(ctx context.Context, in *SetChannelChunkRequest, opts ...grpc.CallOption) (*SetChannelChunkResponse, error)
	GetGuild(ctx context.Context, in *GetGuildRequest, opts ...grpc.CallOption) (*GetGuildResponse, error)
	SetGuild(ctx context.Context, in *SetGuildRequest, opts ...grpc.CallOption) (*SetGuildResponse, error)
	UpdateGuild(ctx context.Context, in *UpdateGuildRequest, opts ...grpc.CallOption) (*UpdateGuildResponse, error)
	DeleteGuild(ctx context.Context, in *DeleteGuildRequest, opts ...grpc.CallOption) (*DeleteGuildResponse, error)
	GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error)
	SetMember(ctx context.Context, in *SetMemberRequest, opts ...grpc.CallOption) (*SetMemberResponse, error)
	UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*UpdateMemberResponse, error)
	DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*DeleteMemberResponse, error)
	SetMemberChunk(ctx context.Context, in *SetMemberChunkRequest, opts ...grpc.CallOption) (*SetMemberChunkResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	SetUser(ctx context.Context, in *SetUserRequest, opts ...grpc.CallOption) (*SetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	SetMessage(ctx context.Context, in *SetMessageRequest, opts ...grpc.CallOption) (*SetMessageResponse, error)
	UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
	GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error)
	SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error)
	UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error)
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error)
	SetRoleChunk(ctx context.Context, in *SetRoleChunkRequest, opts ...grpc.CallOption) (*SetRoleChunkResponse, error)
	CheckOps(ctx context.Context, in *CheckOpsRequest, opts ...grpc.CallOption) (*CheckOpsResponse, error)
}

type stateClient struct {
	cc *grpc.ClientConn
}

func NewStateClient(cc *grpc.ClientConn) StateClient {
	return &stateClient{cc}
}

func (c *stateClient) GetChannel(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*GetChannelResponse, error) {
	out := new(GetChannelResponse)
	err := c.cc.Invoke(ctx, "/state.State/GetChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetChannel(ctx context.Context, in *SetChannelRequest, opts ...grpc.CallOption) (*SetChannelResponse, error) {
	out := new(SetChannelResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*UpdateChannelResponse, error) {
	out := new(UpdateChannelResponse)
	err := c.cc.Invoke(ctx, "/state.State/UpdateChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) DeleteChannel(ctx context.Context, in *DeleteChannelRequest, opts ...grpc.CallOption) (*DeleteChannelResponse, error) {
	out := new(DeleteChannelResponse)
	err := c.cc.Invoke(ctx, "/state.State/DeleteChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetChannelChunk(ctx context.Context, in *SetChannelChunkRequest, opts ...grpc.CallOption) (*SetChannelChunkResponse, error) {
	out := new(SetChannelChunkResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetChannelChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetGuild(ctx context.Context, in *GetGuildRequest, opts ...grpc.CallOption) (*GetGuildResponse, error) {
	out := new(GetGuildResponse)
	err := c.cc.Invoke(ctx, "/state.State/GetGuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetGuild(ctx context.Context, in *SetGuildRequest, opts ...grpc.CallOption) (*SetGuildResponse, error) {
	out := new(SetGuildResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetGuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) UpdateGuild(ctx context.Context, in *UpdateGuildRequest, opts ...grpc.CallOption) (*UpdateGuildResponse, error) {
	out := new(UpdateGuildResponse)
	err := c.cc.Invoke(ctx, "/state.State/UpdateGuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) DeleteGuild(ctx context.Context, in *DeleteGuildRequest, opts ...grpc.CallOption) (*DeleteGuildResponse, error) {
	out := new(DeleteGuildResponse)
	err := c.cc.Invoke(ctx, "/state.State/DeleteGuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error) {
	out := new(GetMemberResponse)
	err := c.cc.Invoke(ctx, "/state.State/GetMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetMember(ctx context.Context, in *SetMemberRequest, opts ...grpc.CallOption) (*SetMemberResponse, error) {
	out := new(SetMemberResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*UpdateMemberResponse, error) {
	out := new(UpdateMemberResponse)
	err := c.cc.Invoke(ctx, "/state.State/UpdateMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*DeleteMemberResponse, error) {
	out := new(DeleteMemberResponse)
	err := c.cc.Invoke(ctx, "/state.State/DeleteMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetMemberChunk(ctx context.Context, in *SetMemberChunkRequest, opts ...grpc.CallOption) (*SetMemberChunkResponse, error) {
	out := new(SetMemberChunkResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetMemberChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/state.State/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetUser(ctx context.Context, in *SetUserRequest, opts ...grpc.CallOption) (*SetUserResponse, error) {
	out := new(SetUserResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/state.State/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/state.State/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, "/state.State/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetMessage(ctx context.Context, in *SetMessageRequest, opts ...grpc.CallOption) (*SetMessageResponse, error) {
	out := new(SetMessageResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error) {
	out := new(UpdateMessageResponse)
	err := c.cc.Invoke(ctx, "/state.State/UpdateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	out := new(DeleteMessageResponse)
	err := c.cc.Invoke(ctx, "/state.State/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error) {
	out := new(GetRoleResponse)
	err := c.cc.Invoke(ctx, "/state.State/GetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error) {
	out := new(SetRoleResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error) {
	out := new(UpdateRoleResponse)
	err := c.cc.Invoke(ctx, "/state.State/UpdateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error) {
	out := new(DeleteRoleResponse)
	err := c.cc.Invoke(ctx, "/state.State/DeleteRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) SetRoleChunk(ctx context.Context, in *SetRoleChunkRequest, opts ...grpc.CallOption) (*SetRoleChunkResponse, error) {
	out := new(SetRoleChunkResponse)
	err := c.cc.Invoke(ctx, "/state.State/SetRoleChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) CheckOps(ctx context.Context, in *CheckOpsRequest, opts ...grpc.CallOption) (*CheckOpsResponse, error) {
	out := new(CheckOpsResponse)
	err := c.cc.Invoke(ctx, "/state.State/CheckOps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServer is the server API for State service.
type StateServer interface {
	GetChannel(context.Context, *GetChannelRequest) (*GetChannelResponse, error)
	SetChannel(context.Context, *SetChannelRequest) (*SetChannelResponse, error)
	UpdateChannel(context.Context, *UpdateChannelRequest) (*UpdateChannelResponse, error)
	DeleteChannel(context.Context, *DeleteChannelRequest) (*DeleteChannelResponse, error)
	SetChannelChunk(context.Context, *SetChannelChunkRequest) (*SetChannelChunkResponse, error)
	GetGuild(context.Context, *GetGuildRequest) (*GetGuildResponse, error)
	SetGuild(context.Context, *SetGuildRequest) (*SetGuildResponse, error)
	UpdateGuild(context.Context, *UpdateGuildRequest) (*UpdateGuildResponse, error)
	DeleteGuild(context.Context, *DeleteGuildRequest) (*DeleteGuildResponse, error)
	GetMember(context.Context, *GetMemberRequest) (*GetMemberResponse, error)
	SetMember(context.Context, *SetMemberRequest) (*SetMemberResponse, error)
	UpdateMember(context.Context, *UpdateMemberRequest) (*UpdateMemberResponse, error)
	DeleteMember(context.Context, *DeleteMemberRequest) (*DeleteMemberResponse, error)
	SetMemberChunk(context.Context, *SetMemberChunkRequest) (*SetMemberChunkResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	SetUser(context.Context, *SetUserRequest) (*SetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	SetMessage(context.Context, *SetMessageRequest) (*SetMessageResponse, error)
	UpdateMessage(context.Context, *UpdateMessageRequest) (*UpdateMessageResponse, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error)
	GetRole(context.Context, *GetRoleRequest) (*GetRoleResponse, error)
	SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error)
	UpdateRole(context.Context, *UpdateRoleRequest) (*UpdateRoleResponse, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleResponse, error)
	SetRoleChunk(context.Context, *SetRoleChunkRequest) (*SetRoleChunkResponse, error)
	CheckOps(context.Context, *CheckOpsRequest) (*CheckOpsResponse, error)
}

func RegisterStateServer(s *grpc.Server, srv StateServer) {
	s.RegisterService(&_State_serviceDesc, srv)
}

func _State_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/GetChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetChannel(ctx, req.(*GetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetChannel(ctx, req.(*SetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_UpdateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).UpdateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/UpdateChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).UpdateChannel(ctx, req.(*UpdateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_DeleteChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).DeleteChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/DeleteChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).DeleteChannel(ctx, req.(*DeleteChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetChannelChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChannelChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetChannelChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetChannelChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetChannelChunk(ctx, req.(*SetChannelChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/GetGuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetGuild(ctx, req.(*GetGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetGuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetGuild(ctx, req.(*SetGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_UpdateGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).UpdateGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/UpdateGuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).UpdateGuild(ctx, req.(*UpdateGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_DeleteGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).DeleteGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/DeleteGuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).DeleteGuild(ctx, req.(*DeleteGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/GetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetMember(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetMember(ctx, req.(*SetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_UpdateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).UpdateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/UpdateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).UpdateMember(ctx, req.(*UpdateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/DeleteMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).DeleteMember(ctx, req.(*DeleteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetMemberChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetMemberChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetMemberChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetMemberChunk(ctx, req.(*SetMemberChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetUser(ctx, req.(*SetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetMessage(ctx, req.(*SetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/UpdateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).UpdateMessage(ctx, req.(*UpdateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetRole(ctx, req.(*GetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetRole(ctx, req.(*SetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/UpdateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).UpdateRole(ctx, req.(*UpdateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/DeleteRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_SetRoleChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).SetRoleChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/SetRoleChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).SetRoleChunk(ctx, req.(*SetRoleChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_CheckOps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).CheckOps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/state.State/CheckOps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).CheckOps(ctx, req.(*CheckOpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _State_serviceDesc = grpc.ServiceDesc{
	ServiceName: "state.State",
	HandlerType: (*StateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChannel",
			Handler:    _State_GetChannel_Handler,
		},
		{
			MethodName: "SetChannel",
			Handler:    _State_SetChannel_Handler,
		},
		{
			MethodName: "UpdateChannel",
			Handler:    _State_UpdateChannel_Handler,
		},
		{
			MethodName: "DeleteChannel",
			Handler:    _State_DeleteChannel_Handler,
		},
		{
			MethodName: "SetChannelChunk",
			Handler:    _State_SetChannelChunk_Handler,
		},
		{
			MethodName: "GetGuild",
			Handler:    _State_GetGuild_Handler,
		},
		{
			MethodName: "SetGuild",
			Handler:    _State_SetGuild_Handler,
		},
		{
			MethodName: "UpdateGuild",
			Handler:    _State_UpdateGuild_Handler,
		},
		{
			MethodName: "DeleteGuild",
			Handler:    _State_DeleteGuild_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _State_GetMember_Handler,
		},
		{
			MethodName: "SetMember",
			Handler:    _State_SetMember_Handler,
		},
		{
			MethodName: "UpdateMember",
			Handler:    _State_UpdateMember_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _State_DeleteMember_Handler,
		},
		{
			MethodName: "SetMemberChunk",
			Handler:    _State_SetMemberChunk_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _State_GetUser_Handler,
		},
		{
			MethodName: "SetUser",
			Handler:    _State_SetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _State_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _State_DeleteUser_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _State_GetMessage_Handler,
		},
		{
			MethodName: "SetMessage",
			Handler:    _State_SetMessage_Handler,
		},
		{
			MethodName: "UpdateMessage",
			Handler:    _State_UpdateMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _State_DeleteMessage_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _State_GetRole_Handler,
		},
		{
			MethodName: "SetRole",
			Handler:    _State_SetRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _State_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _State_DeleteRole_Handler,
		},
		{
			MethodName: "SetRoleChunk",
			Handler:    _State_SetRoleChunk_Handler,
		},
		{
			MethodName: "CheckOps",
			Handler:    _State_CheckOps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "state.proto",
}

func init() { proto.RegisterFile("state.proto", fileDescriptor_state_14d3cd47de5caa95) }

var fileDescriptor_state_14d3cd47de5caa95 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x95, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0x53, 0xa4, 0xf2, 0xc7, 0x49, 0xa8, 0xb4, 0x12, 0x25, 0xd9, 0xa4, 0x7b, 0xe0, 0x01,
	0x7a, 0x80, 0x1b, 0x12, 0x12, 0x62, 0x11, 0xab, 0x4a, 0xa0, 0x4a, 0xb1, 0x7a, 0xe1, 0x96, 0xb4,
	0xa3, 0x06, 0x75, 0x93, 0x5d, 0x62, 0xe7, 0x3d, 0x78, 0x12, 0x9e, 0x83, 0x63, 0x8f, 0x1c, 0x51,
	0xf2, 0x22, 0x68, 0xed, 0xb5, 0xd7, 0x33, 0x9e, 0xbd, 0xc5, 0xdf, 0xd7, 0xef, 0x57, 0x7b, 0xfa,
	0x65, 0x2a, 0x86, 0x4a, 0x2f, 0x35, 0x5c, 0xd6, 0xbb, 0x4a, 0x57, 0xc9, 0xa9, 0x39, 0xa4, 0xe3,
	0xdb, 0xf5, 0x72, 0xbb, 0x85, 0xd2, 0xaa, 0xe9, 0xf0, 0x7e, 0xff, 0xa3, 0xbc, 0x6b, 0x0f, 0xa3,
	0x0d, 0x6c, 0x56, 0xb0, 0x6b, 0x4f, 0x62, 0xaf, 0xfc, 0xe7, 0xf1, 0x06, 0x94, 0x5a, 0xde, 0x83,
	0xb3, 0x76, 0x55, 0xd9, 0x7e, 0x7e, 0xfb, 0xfb, 0x4c, 0x9c, 0xca, 0x06, 0x9d, 0xe4, 0x42, 0x14,
	0xa0, 0x73, 0xcb, 0x4f, 0x26, 0x97, 0xf6, 0xb7, 0x77, 0xd2, 0x02, 0x7e, 0xee, 0x41, 0xe9, 0x74,
	0xca, 0x38, 0xaa, 0xae, 0xb6, 0x0a, 0xde, 0x0c, 0x1a, 0x88, 0x8c, 0x21, 0xb2, 0x17, 0x22, 0x39,
	0xc8, 0x57, 0x31, 0xbe, 0xa9, 0xef, 0x96, 0x1a, 0x1c, 0x67, 0xd6, 0xfe, 0x34, 0x52, 0x1d, 0x6a,
	0xce, 0x9b, 0x21, 0xed, 0x33, 0x94, 0x10, 0xd3, 0x90, 0x4a, 0x69, 0xc4, 0xf4, 0xb4, 0x85, 0x38,
	0xeb, 0xee, 0x9c, 0xaf, 0xf7, 0xdb, 0x87, 0xe4, 0x22, 0x7a, 0x8b, 0xd1, 0x1d, 0x31, 0xeb, 0xb3,
	0x3d, 0xf3, 0x83, 0x78, 0x5e, 0x80, 0x2e, 0x9a, 0x3f, 0x65, 0x72, 0xde, 0x4d, 0xd7, 0x08, 0x8e,
	0xf2, 0x3a, 0xd2, 0xc3, 0xb8, 0xa4, 0x71, 0xd9, 0x13, 0x97, 0x71, 0xfc, 0x8b, 0x18, 0xda, 0xd1,
	0x59, 0xc2, 0x14, 0x8d, 0x13, 0x41, 0x52, 0xce, 0x0a, 0x39, 0x76, 0x68, 0x98, 0x13, 0x68, 0x94,
	0x83, 0x2c, 0xcf, 0xf9, 0x28, 0x5e, 0x14, 0xa0, 0xbf, 0x99, 0x2e, 0x27, 0xc1, 0xb3, 0xad, 0xe2,
	0x18, 0x93, 0xd8, 0x08, 0x09, 0x32, 0x22, 0xc8, 0x3e, 0x82, 0x64, 0x08, 0x57, 0x62, 0x64, 0x1f,
	0xd9, 0x42, 0xf0, 0xcb, 0x31, 0x67, 0xc6, 0x7a, 0x21, 0xca, 0xbe, 0x93, 0xa0, 0x42, 0x91, 0xa2,
	0xb0, 0xe7, 0x51, 0xd7, 0xe2, 0xa5, 0xbf, 0xac, 0xad, 0xde, 0x9c, 0xbe, 0x01, 0x35, 0xef, 0xa2,
	0xc7, 0xf5, 0xc0, 0xf7, 0xe2, 0x59, 0x01, 0xfa, 0x46, 0xc1, 0x2e, 0x79, 0xd5, 0xcd, 0xb3, 0x39,
	0x3b, 0xc4, 0x39, 0x95, 0xc3, 0xac, 0x24, 0x59, 0xc9, 0x67, 0x65, 0x94, 0xcd, 0x85, 0xb0, 0xd3,
	0x32, 0xf1, 0x09, 0x1a, 0x60, 0x48, 0x98, 0x32, 0x4e, 0x08, 0xb1, 0x73, 0x42, 0x90, 0x4e, 0xa2,
	0x90, 0xd0, 0x09, 0x21, 0xa6, 0x41, 0x66, 0x3d, 0x26, 0xa8, 0x54, 0x46, 0x62, 0x96, 0x9e, 0x77,
	0xc8, 0xd2, 0xa3, 0x10, 0xd9, 0x0b, 0x91, 0x1c, 0xc4, 0x2f, 0x3d, 0xc7, 0xa1, 0xbd, 0x42, 0xa8,
	0x39, 0x6f, 0xc6, 0x4b, 0x8f, 0xd2, 0x90, 0xca, 0x2f, 0xbd, 0x98, 0x66, 0x7b, 0xb2, 0xa8, 0x4a,
	0x08, 0x7b, 0xd2, 0x9c, 0x99, 0x9e, 0x58, 0x99, 0xf4, 0x04, 0x65, 0x25, 0x9f, 0x95, 0x51, 0xd6,
	0xf7, 0xc4, 0xc4, 0x71, 0x4f, 0x42, 0xc2, 0x94, 0x71, 0xe2, 0x9e, 0x20, 0x48, 0x27, 0xf1, 0x3d,
	0x21, 0x90, 0x2b, 0x31, 0x6a, 0xaf, 0x67, 0xbf, 0x78, 0x29, 0xbe, 0x33, 0xfa, 0xda, 0xcd, 0x58,
	0x2f, 0x5c, 0xd7, 0xf9, 0x1a, 0x6e, 0x1f, 0xae, 0x6b, 0xe5, 0xd7, 0xb5, 0x13, 0xe8, 0xba, 0xee,
	0x74, 0x17, 0xff, 0x34, 0xff, 0x73, 0xc8, 0x4e, 0x1e, 0x0f, 0xd9, 0xc9, 0xbf, 0x43, 0x76, 0xf2,
	0xeb, 0x98, 0x0d, 0x1e, 0x8f, 0xd9, 0xe0, 0xef, 0x31, 0x1b, 0x7c, 0x7f, 0x52, 0xaf, 0x56, 0x4f,
	0xcd, 0x7f, 0xf5, 0x77, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x88, 0x3b, 0x2f, 0x3c, 0x08,
	0x00, 0x00,
}
